baseURL: http://example.org/
languageCode: en-us
title: Code with Flavor
theme: PaperMod

params:
  defaultTheme: auto
  enableEmoji: true

  homeInfoParams:
        Title: Code with Flavor ğŸ’»ğŸ´ 
        Content: Can be Info, links, about...
